name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # TODO: actions/cacheを用いてここにキャッシュ機構を書くべきだが，何をキャッシュすれば良いのか不明．
      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/v2.0.1/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - run: lake build
